import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`antialiased ${inter.className}`}>
            <Header />
            <div className="mt-[84px]">{children}</div>
            <Footer />
         </body>
      </html>
   );
}
