import type { Metadata } from "next"
import "./globals.css"
import Providers from "@/providers"
import { Tenor_Sans } from "next/font/google"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

const tenor_Sans = Tenor_Sans({
   weight: "400",
   subsets: ["latin"],
})

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`antialiased ${tenor_Sans.className}`}>
            <Providers>{children}</Providers>
         </body>
      </html>
   )
}
