import type { Metadata } from "next"
import Header from "@/components/Header/Header"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <div className="background">
         <Header />
         <main
            className="background"
            style={{
               minHeight: "calc(100vh - 56px)",
            }}
         >
            {children}
         </main>
      </div>
   )
}
