import type { Metadata } from "next"
import Header from "@/components/Header/Header"
import Footer from "@/components/Footer/Footer"
import Breadcrumb from "@/components/UI/Breadcrumb"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <>
         <Header />
         <main className="mt-[var(--header-height)]">
            <div className="w-full">
               <Breadcrumb />
            </div>
            {children}
         </main>
         <Footer />
      </>
   )
}
